[package]
name = "getargv-sys"
links = "getargv"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
readme = "README.md"
authors = ["CamJN <getargv@narzt.cam>"]
homepage = "https://getargv.narzt.cam/"
documentation = "https://getargv.narzt.cam/rustdocs"
repository = "https://github.com/getargv/getargv-sys/"
description = "The first and only library to provide a correct interface to the KERN_PROCARGS2 sysctl."
categories = ["external-ffi-bindings", "os::macos-apis"]
keywords = ["argv", "arguments", "macOS", "KERN_PROCARGS2", "sysctl"]

[build-dependencies]
bindgen = "0.61.0"
